import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';
import { PrismaClient } from '../generated/prisma/client';

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
});

const ASSETS = [
  // Doors
  {
    category: 'DOOR',
    name: 'Single Door',
    defaultWidthMm: 900,
    defaultDepthMm: 40,
    defaultHeightMm: 2100,
    color: '#8B5E3C',
  },
  {
    category: 'DOOR',
    name: 'Double Door',
    defaultWidthMm: 1500,
    defaultDepthMm: 40,
    defaultHeightMm: 2100,
    color: '#8B5E3C',
  },
  {
    category: 'DOOR',
    name: 'Sliding Door',
    defaultWidthMm: 1800,
    defaultDepthMm: 60,
    defaultHeightMm: 2100,
    color: '#A9834B',
  },

  // Windows
  {
    category: 'WINDOW',
    name: 'Single Window',
    defaultWidthMm: 900,
    defaultDepthMm: 30,
    defaultHeightMm: 1200,
    color: '#7EC8E3',
  },
  {
    category: 'WINDOW',
    name: 'Double Window',
    defaultWidthMm: 1500,
    defaultDepthMm: 30,
    defaultHeightMm: 1200,
    color: '#7EC8E3',
  },
  {
    category: 'WINDOW',
    name: 'Bay Window',
    defaultWidthMm: 2000,
    defaultDepthMm: 300,
    defaultHeightMm: 1400,
    color: '#A6D8EF',
  },

  // Furniture
  {
    category: 'FURNITURE',
    name: 'Sofa (3-seater)',
    defaultWidthMm: 2000,
    defaultDepthMm: 900,
    defaultHeightMm: 800,
    color: '#C97B63',
  },
  {
    category: 'FURNITURE',
    name: 'Armchair',
    defaultWidthMm: 800,
    defaultDepthMm: 850,
    defaultHeightMm: 800,
    color: '#C97B63',
  },
  {
    category: 'FURNITURE',
    name: 'Coffee Table',
    defaultWidthMm: 1100,
    defaultDepthMm: 600,
    defaultHeightMm: 400,
    color: '#B08968',
  },
  {
    category: 'FURNITURE',
    name: 'Dining Table (6-seat)',
    defaultWidthMm: 1800,
    defaultDepthMm: 900,
    defaultHeightMm: 750,
    color: '#B08968',
  },
  {
    category: 'FURNITURE',
    name: 'Dining Chair',
    defaultWidthMm: 450,
    defaultDepthMm: 500,
    defaultHeightMm: 900,
    color: '#9C6B4F',
  },
  {
    category: 'FURNITURE',
    name: 'Double Bed',
    defaultWidthMm: 1500,
    defaultDepthMm: 2000,
    defaultHeightMm: 500,
    color: '#6D8CA6',
  },
  {
    category: 'FURNITURE',
    name: 'Single Bed',
    defaultWidthMm: 900,
    defaultDepthMm: 2000,
    defaultHeightMm: 500,
    color: '#6D8CA6',
  },
  {
    category: 'FURNITURE',
    name: 'Wardrobe',
    defaultWidthMm: 1200,
    defaultDepthMm: 600,
    defaultHeightMm: 2100,
    color: '#7A6355',
  },
  {
    category: 'FURNITURE',
    name: 'TV Table',
    defaultWidthMm: 1400,
    defaultDepthMm: 450,
    defaultHeightMm: 450,
    color: '#7A6355',
  },
  {
    category: 'FURNITURE',
    name: 'Study Table',
    defaultWidthMm: 1200,
    defaultDepthMm: 600,
    defaultHeightMm: 750,
    color: '#B08968',
  },
  {
    category: 'FURNITURE',
    name: 'Bookshelf',
    defaultWidthMm: 900,
    defaultDepthMm: 300,
    defaultHeightMm: 1800,
    color: '#7A6355',
  },
  {
    category: 'FURNITURE',
    name: 'Recliner Chair',
    defaultWidthMm: 850,
    defaultDepthMm: 900,
    defaultHeightMm: 1000,
    color: '#9C7B63',
  },
  {
    category: 'FURNITURE',
    name: 'Bar Stool',
    defaultWidthMm: 350,
    defaultDepthMm: 350,
    defaultHeightMm: 750,
    color: '#7A6355',
  },
  {
    category: 'FURNITURE',
    name: 'Nightstand',
    defaultWidthMm: 500,
    defaultDepthMm: 400,
    defaultHeightMm: 550,
    color: '#7A6355',
  },
  {
    category: 'FURNITURE',
    name: 'Shoe Rack',
    defaultWidthMm: 800,
    defaultDepthMm: 300,
    defaultHeightMm: 900,
    color: '#7A6355',
  },
  {
    category: 'FURNITURE',
    name: 'Console Table',
    defaultWidthMm: 1200,
    defaultDepthMm: 350,
    defaultHeightMm: 800,
    color: '#B08968',
  },
  {
    category: 'FURNITURE',
    name: 'Staircase',
    defaultWidthMm: 1000,
    defaultDepthMm: 3000,
    defaultHeightMm: 2700,
    color: '#B08968',
  },
  {
    category: 'FURNITURE',
    name: 'Interior Staircase',
    defaultWidthMm: 2000,
    defaultDepthMm: 2400,
    defaultHeightMm: 2700,
    color: '#A9835B',
  },
  {
    category: 'FURNITURE',
    name: 'Closed Riser Staircase',
    defaultWidthMm: 1000,
    defaultDepthMm: 3000,
    defaultHeightMm: 2700,
    color: '#B08968',
  },
  {
    category: 'FURNITURE',
    name: 'L-Shaped Staircase',
    defaultWidthMm: 2200,
    defaultDepthMm: 2200,
    defaultHeightMm: 2700,
    color: '#B08968',
  },
  {
    category: 'FURNITURE',
    name: 'Television',
    defaultWidthMm: 1200,
    defaultDepthMm: 250,
    defaultHeightMm: 800,
    color: '#3a6ea5',
  },
  {
    category: 'FURNITURE',
    name: 'Wall Mounted TV',
    defaultWidthMm: 1200,
    defaultDepthMm: 80,
    defaultHeightMm: 700,
    color: '#3a6ea5',
  },
  {
    category: 'FURNITURE',
    name: 'Showcase',
    defaultWidthMm: 900,
    defaultDepthMm: 400,
    defaultHeightMm: 1800,
    color: '#7A5C3E',
  },
  {
    category: 'FURNITURE',
    name: 'Pooja Mandir',
    defaultWidthMm: 900,
    defaultDepthMm: 450,
    defaultHeightMm: 1800,
    color: '#8B5E3C',
  },

  // Kitchen
  {
    category: 'KITCHEN',
    name: 'Kitchen Counter',
    defaultWidthMm: 2400,
    defaultDepthMm: 600,
    defaultHeightMm: 900,
    color: '#8E9AAF',
  },
  {
    category: 'KITCHEN',
    name: 'Kitchen Island',
    defaultWidthMm: 1800,
    defaultDepthMm: 900,
    defaultHeightMm: 900,
    color: '#8E9AAF',
  },
  {
    category: 'KITCHEN',
    name: 'Refrigerator',
    defaultWidthMm: 750,
    defaultDepthMm: 700,
    defaultHeightMm: 1800,
    color: '#B5BEC9',
  },
  {
    category: 'KITCHEN',
    name: 'Kitchen Sink',
    defaultWidthMm: 800,
    defaultDepthMm: 600,
    defaultHeightMm: 900,
    color: '#8E9AAF',
  },
  {
    category: 'KITCHEN',
    name: 'Stove',
    defaultWidthMm: 750,
    defaultDepthMm: 650,
    defaultHeightMm: 900,
    color: '#3A3A3A',
  },
  {
    category: 'KITCHEN',
    name: 'Microwave',
    defaultWidthMm: 500,
    defaultDepthMm: 400,
    defaultHeightMm: 300,
    color: '#4A4A4A',
  },
  {
    category: 'KITCHEN',
    name: 'Chimney (Range Hood)',
    defaultWidthMm: 750,
    defaultDepthMm: 500,
    defaultHeightMm: 600,
    color: '#B5BEC9',
  },
  {
    category: 'KITCHEN',
    name: 'Double Door Refrigerator',
    defaultWidthMm: 900,
    defaultDepthMm: 700,
    defaultHeightMm: 1800,
    color: '#C7CDD6',
  },
  {
    category: 'KITCHEN',
    name: 'Dishwasher',
    defaultWidthMm: 600,
    defaultDepthMm: 600,
    defaultHeightMm: 850,
    color: '#D9DCE1',
  },
  {
    category: 'KITCHEN',
    name: 'Induction Cooktop',
    defaultWidthMm: 750,
    defaultDepthMm: 500,
    defaultHeightMm: 60,
    color: '#1C1C1C',
  },
  {
    category: 'KITCHEN',
    name: 'Kitchen Cupboard',
    defaultWidthMm: 900,
    defaultDepthMm: 600,
    defaultHeightMm: 2100,
    color: '#A9835B',
  },

  // Bathroom
  {
    category: 'BATHROOM',
    name: 'Toilet',
    defaultWidthMm: 400,
    defaultDepthMm: 650,
    defaultHeightMm: 800,
    color: '#E4E9EE',
  },
  {
    category: 'BATHROOM',
    name: 'Wash Basin',
    defaultWidthMm: 600,
    defaultDepthMm: 450,
    defaultHeightMm: 850,
    color: '#E4E9EE',
  },
  {
    category: 'BATHROOM',
    name: 'Bathtub',
    defaultWidthMm: 1700,
    defaultDepthMm: 750,
    defaultHeightMm: 550,
    color: '#DCE6EC',
  },
  {
    category: 'BATHROOM',
    name: 'Shower',
    defaultWidthMm: 900,
    defaultDepthMm: 900,
    defaultHeightMm: 2000,
    color: '#CBD9E1',
  },
  {
    category: 'BATHROOM',
    name: 'Mirror Cabinet',
    defaultWidthMm: 600,
    defaultDepthMm: 150,
    defaultHeightMm: 700,
    color: '#CDE8EE',
  },
  {
    category: 'BATHROOM',
    name: 'Towel Rack',
    defaultWidthMm: 600,
    defaultDepthMm: 100,
    defaultHeightMm: 100,
    color: '#B5BEC9',
  },
  {
    category: 'BATHROOM',
    name: 'Bidet',
    defaultWidthMm: 400,
    defaultDepthMm: 550,
    defaultHeightMm: 400,
    color: '#E4E9EE',
  },

  // Electrical
  {
    category: 'ELECTRICAL',
    name: 'Ceiling Fan',
    defaultWidthMm: 1200,
    defaultDepthMm: 1200,
    defaultHeightMm: 300,
    color: '#C9C9C9',
  },
  {
    category: 'ELECTRICAL',
    name: 'AC Unit',
    defaultWidthMm: 900,
    defaultDepthMm: 250,
    defaultHeightMm: 300,
    color: '#DDE2E5',
  },
  {
    category: 'ELECTRICAL',
    name: 'Water Heater',
    defaultWidthMm: 450,
    defaultDepthMm: 450,
    defaultHeightMm: 1200,
    color: '#C9C9C9',
  },
  {
    category: 'ELECTRICAL',
    name: 'Exhaust Fan',
    defaultWidthMm: 300,
    defaultDepthMm: 300,
    defaultHeightMm: 300,
    color: '#DDE2E5',
  },
  {
    category: 'ELECTRICAL',
    name: 'Wall Light',
    defaultWidthMm: 200,
    defaultDepthMm: 150,
    defaultHeightMm: 250,
    color: '#F0D9A0',
  },
  {
    category: 'ELECTRICAL',
    name: 'Switch Board',
    defaultWidthMm: 150,
    defaultDepthMm: 10,
    defaultHeightMm: 100,
    color: '#F2F2F0',
  },
  {
    category: 'ELECTRICAL',
    name: 'Bulb',
    defaultWidthMm: 100,
    defaultDepthMm: 100,
    defaultHeightMm: 200,
    color: '#FFE9B3',
  },
  {
    category: 'ELECTRICAL',
    name: 'Washing Machine',
    defaultWidthMm: 600,
    defaultDepthMm: 600,
    defaultHeightMm: 850,
    color: '#E7E9EC',
  },
  {
    category: 'ELECTRICAL',
    name: 'Clothes Dryer',
    defaultWidthMm: 600,
    defaultDepthMm: 600,
    defaultHeightMm: 850,
    color: '#DADDE0',
  },

  // Decoration
  {
    category: 'DECORATION',
    name: 'Potted Plant',
    defaultWidthMm: 400,
    defaultDepthMm: 400,
    defaultHeightMm: 900,
    color: '#5B8C5A',
  },
  {
    category: 'DECORATION',
    name: 'Area Rug',
    defaultWidthMm: 2000,
    defaultDepthMm: 1400,
    defaultHeightMm: 10,
    color: '#D8B384',
  },
  {
    category: 'DECORATION',
    name: 'Wall Mirror',
    defaultWidthMm: 700,
    defaultDepthMm: 30,
    defaultHeightMm: 900,
    color: '#CDE8EE',
  },
  {
    category: 'DECORATION',
    name: 'Wall Clock',
    defaultWidthMm: 350,
    defaultDepthMm: 40,
    defaultHeightMm: 350,
    color: '#2B2B2B',
  },
  {
    category: 'DECORATION',
    name: 'Floor Lamp',
    defaultWidthMm: 350,
    defaultDepthMm: 350,
    defaultHeightMm: 1500,
    color: '#D8D2C4',
  },
  {
    category: 'DECORATION',
    name: 'Curtains',
    defaultWidthMm: 1600,
    defaultDepthMm: 150,
    defaultHeightMm: 2200,
    color: '#C9B79C',
  },
  {
    category: 'DECORATION',
    name: 'Sheer Curtains',
    defaultWidthMm: 1600,
    defaultDepthMm: 100,
    defaultHeightMm: 2200,
    color: '#EDE6D6',
  },
  {
    category: 'DECORATION',
    name: 'Blackout Curtains',
    defaultWidthMm: 1600,
    defaultDepthMm: 150,
    defaultHeightMm: 2200,
    color: '#3B3630',
  },
  {
    category: 'DECORATION',
    name: 'Long Curtains',
    defaultWidthMm: 1800,
    defaultDepthMm: 150,
    defaultHeightMm: 2600,
    color: '#B99C7A',
  },
  {
    category: 'DECORATION',
    name: 'Patterned Curtains',
    defaultWidthMm: 1600,
    defaultDepthMm: 150,
    defaultHeightMm: 2200,
    color: '#9C6B4F',
  },
  {
    category: 'DECORATION',
    name: 'Curtain Valance',
    defaultWidthMm: 1600,
    defaultDepthMm: 150,
    defaultHeightMm: 400,
    color: '#C9B79C',
  },

  // Exterior / landscaping
  {
    category: 'EXTERIOR',
    name: 'House Base / Plinth',
    defaultWidthMm: 8000,
    defaultDepthMm: 8000,
    defaultHeightMm: 300,
    color: '#9a9a9a',
  },
  {
    category: 'EXTERIOR',
    name: 'Tree (Large)',
    defaultWidthMm: 3000,
    defaultDepthMm: 3000,
    defaultHeightMm: 5000,
    color: '#3F6B3A',
  },
  {
    category: 'EXTERIOR',
    name: 'Tree (Small)',
    defaultWidthMm: 1500,
    defaultDepthMm: 1500,
    defaultHeightMm: 2500,
    color: '#4E7A48',
  },
  {
    category: 'EXTERIOR',
    name: 'Garden Hedge',
    defaultWidthMm: 2000,
    defaultDepthMm: 400,
    defaultHeightMm: 800,
    color: '#5B8C5A',
  },
  {
    category: 'EXTERIOR',
    name: 'Swimming Pool',
    defaultWidthMm: 6000,
    defaultDepthMm: 3000,
    defaultHeightMm: 100,
    color: '#5AA9C9',
  },
  {
    category: 'EXTERIOR',
    name: 'Boundary Wall',
    defaultWidthMm: 3000,
    defaultDepthMm: 200,
    defaultHeightMm: 1800,
    color: '#9C9284',
  },
  {
    category: 'EXTERIOR',
    name: 'Hand Grill',
    defaultWidthMm: 3000,
    defaultDepthMm: 50,
    defaultHeightMm: 900,
    color: '#2B2B2B',
  },
  {
    category: 'EXTERIOR',
    name: 'Main Gate',
    defaultWidthMm: 2400,
    defaultDepthMm: 100,
    defaultHeightMm: 1800,
    color: '#4A4A4A',
  },
  {
    category: 'EXTERIOR',
    name: 'Driveway Panel',
    defaultWidthMm: 3000,
    defaultDepthMm: 3000,
    defaultHeightMm: 20,
    color: '#A9A29A',
  },
  {
    category: 'EXTERIOR',
    name: 'Pathway Panel',
    defaultWidthMm: 900,
    defaultDepthMm: 900,
    defaultHeightMm: 20,
    color: '#BFB6A8',
  },
  {
    category: 'EXTERIOR',
    name: 'Outdoor Sofa',
    defaultWidthMm: 1800,
    defaultDepthMm: 800,
    defaultHeightMm: 700,
    color: '#8A6F5C',
  },
  {
    category: 'EXTERIOR',
    name: 'Outdoor Dining Table',
    defaultWidthMm: 1600,
    defaultDepthMm: 900,
    defaultHeightMm: 750,
    color: '#7A6355',
  },
  {
    category: 'EXTERIOR',
    name: 'Garden Light',
    defaultWidthMm: 200,
    defaultDepthMm: 200,
    defaultHeightMm: 900,
    color: '#D8D2C4',
  },
  {
    category: 'EXTERIOR',
    name: 'Gazebo',
    defaultWidthMm: 3000,
    defaultDepthMm: 3000,
    defaultHeightMm: 2600,
    color: '#B08968',
  },
  {
    category: 'EXTERIOR',
    name: 'Pillar',
    defaultWidthMm: 300,
    defaultDepthMm: 300,
    defaultHeightMm: 2700,
    color: '#E4DCC8',
  },
] as const;

// Heuristic catalog price for the cost estimator, since none of the
// hand-authored ASSETS entries above carry a real one: a category base rate
// scaled by the asset's own bounding-box volume, so a "Double Bed" costs
// more than a "Nightstand" without needing 70+ prices picked by hand.
const CATEGORY_BASE_PRICE_CENTS: Record<string, number> = {
  DOOR: 25000,
  WINDOW: 20000,
  FURNITURE: 15000,
  KITCHEN: 30000,
  BATHROOM: 20000,
  ELECTRICAL: 8000,
  DECORATION: 4000,
  EXTERIOR: 35000,
};

function estimatePriceCents(asset: (typeof ASSETS)[number]): number {
  const volumeM3 =
    (asset.defaultWidthMm * asset.defaultDepthMm * asset.defaultHeightMm) / 1e9;
  const base = CATEGORY_BASE_PRICE_CENTS[asset.category] ?? 10000;
  return Math.round(base * (0.6 + volumeM3 * 4));
}

async function main() {
  for (const asset of ASSETS) {
    const data = { ...asset, priceCents: estimatePriceCents(asset) };
    const existing = await prisma.asset.findFirst({
      where: { name: asset.name },
    });
    if (existing) {
      await prisma.asset.update({ where: { id: existing.id }, data });
    } else {
      await prisma.asset.create({ data });
    }
  }
  console.log(`Seeded ${ASSETS.length} assets.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
